// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.12.4
// source: proto/bank/type/testaja.proto

package bank

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestAja struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromCurrency string  `protobuf:"bytes,1,opt,name=from_currency,proto3" json:"from_currency,omitempty"`
	ToCurrency   string  `protobuf:"bytes,2,opt,name=to_currency,proto3" json:"to_currency,omitempty"`
	Rate         float64 `protobuf:"fixed64,3,opt,name=rate,proto3" json:"rate,omitempty"`
	Timestamp    string  `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *TestAja) Reset() {
	*x = TestAja{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bank_type_testaja_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestAja) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestAja) ProtoMessage() {}

func (x *TestAja) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bank_type_testaja_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestAja.ProtoReflect.Descriptor instead.
func (*TestAja) Descriptor() ([]byte, []int) {
	return file_proto_bank_type_testaja_proto_rawDescGZIP(), []int{0}
}

func (x *TestAja) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *TestAja) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

func (x *TestAja) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *TestAja) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_proto_bank_type_testaja_proto protoreflect.FileDescriptor

var file_proto_bank_type_testaja_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x61, 0x6e, 0x6b, 0x2f, 0x74, 0x79, 0x70,
	0x65, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x61, 0x6a, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x62, 0x61, 0x6e, 0x6b, 0x22, 0x83, 0x01, 0x0a, 0x07, 0x54, 0x65, 0x73, 0x74, 0x41, 0x6a,
	0x61, 0x12, 0x24, 0x0a, 0x0d, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x63, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x6f, 0x5f, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x6f,
	0x5f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x74,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x72, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x42, 0x38, 0x5a, 0x36, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x69, 0x6d, 0x70, 0x61, 0x6d,
	0x75, 0x6e, 0x67, 0x6b, 0x61, 0x73, 0x2f, 0x6d, 0x79, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x2f, 0x67, 0x6f,
	0x2f, 0x62, 0x61, 0x6e, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_bank_type_testaja_proto_rawDescOnce sync.Once
	file_proto_bank_type_testaja_proto_rawDescData = file_proto_bank_type_testaja_proto_rawDesc
)

func file_proto_bank_type_testaja_proto_rawDescGZIP() []byte {
	file_proto_bank_type_testaja_proto_rawDescOnce.Do(func() {
		file_proto_bank_type_testaja_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_bank_type_testaja_proto_rawDescData)
	})
	return file_proto_bank_type_testaja_proto_rawDescData
}

var file_proto_bank_type_testaja_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_bank_type_testaja_proto_goTypes = []interface{}{
	(*TestAja)(nil), // 0: bank.TestAja
}
var file_proto_bank_type_testaja_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_bank_type_testaja_proto_init() }
func file_proto_bank_type_testaja_proto_init() {
	if File_proto_bank_type_testaja_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_bank_type_testaja_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestAja); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_bank_type_testaja_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_bank_type_testaja_proto_goTypes,
		DependencyIndexes: file_proto_bank_type_testaja_proto_depIdxs,
		MessageInfos:      file_proto_bank_type_testaja_proto_msgTypes,
	}.Build()
	File_proto_bank_type_testaja_proto = out.File
	file_proto_bank_type_testaja_proto_rawDesc = nil
	file_proto_bank_type_testaja_proto_goTypes = nil
	file_proto_bank_type_testaja_proto_depIdxs = nil
}
